def eight(): print(8, end="")
def eight(): print(8, end="")
def zero(): print(0, end="")
def zero(): print(0, end="")
def five(): print(5, end="")
def five(): print(5, end="")
def five(): print(5, end="")
def three(): print(3, end="")
def five(): print(5, end="")
def three(): print(3, end="")
def five(): print(5, end="")

eight(), eight(), zero (), zero (), five(), five(), five(), three(), five(), three(), five()